all:
  hosts:
      flow_server:
        ansible_host: "{{ lookup('env', 'FLOW_IP') }}"
        ansible_user: "{{ lookup('env', 'USER') }}"
        ansible_ssh_private_key_file: "{{ lookup('env', 'PRIV_KEY_LOCATION') }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

