- name: Setup Docker on virtual flow_server
  hosts: flow_server
  become: true
  gather_facts: false
  vars:
    container_name: flow-bank
    image_name: ghcr.io/killbash/flow-bank:latest
  tasks:
  
    - name: Wait for the instance to be ready for SSH
      ansible.builtin.wait_for_connection:
        timeout: 300  # Wait up to 5 minutes
        delay: 10     # Wait 10s before first check


    - name: update apt cache
      ansible.builtin.apt:
         update_cache: yes
    
    - name: Install Docker
      ansible.builtin.apt:
         name: docker.io
         state: present

    - name: Ensure docker service is running
      ansible.builtin.service:
        name: docker 
        state: started
        enabled: yes
    - name: Create placeholder app container
      docker_container:
       name: "{{container_name}}"
       image: "{{image_name}}"
       restart_policy: always
       state: stopped
       env:
          NODE_ENV: "{{ lookup('env', 'NODE_ENV') }}"
          PORT: "{{ lookup('env', 'PORT') }}"
          DB_URI: "{{ lookup('env', 'DB_URI') }}"
          JWT_SECRET: "{{ lookup('env', 'JWT_SECRET') }}"
          USD_RESERVE: "{{ lookup('env', 'USD_RESERVE') }}"
          NGN_RESERVE: "{{ lookup('env', 'NGN_RESERVE') }}"
          ADMIN_PASSWORD: "{{ lookup('env', 'ADMIN_PASSWORD') }}"
          ADMIN_EMAIL: "{{ lookup('env', 'ADMIN_EMAIL') }}"
       ports:
          - "3000:3000"
       pull: false   # Don't fail if image doesn't exist yet
       recreate: yes
      ignore_errors: true  # in case image doesn't exist yet

    - name: Run Watchtower to auto-update containers
      docker_container:
        name: watchtower
        image: containrrr/watchtower
        restart_policy: always
        command: "{{container_name}} --cleanup --interval 10"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
