name: Provision and set up server

on:
  push:
    branches:
      - main
  workflow_dispatch: # manual trigger option

jobs:
  deploy:
    environment: 
      name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug env
        run: |
          echo "PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN"
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2-key
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/ec2-key.pub
          chmod 600 ~/.ssh/ec2-key
          chmod 644 ~/.ssh/ec2-key.pub
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUB_KEY }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # or whatever version you're using

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Instal pulumi
        uses: pulumi/actions@v5
      - name: Run infra provisioning
        run: bash ./build.sh
