name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
      - dev

  workflow_dispatch:

jobs:

 preview_and_lint:
    if: github.base_ref == 'main' || github.base_ref == 'dev'
    runs-on: ubuntu-latest
    environment:
      name: main
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2-key
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/ec2-key.pub
          chmod 600 ~/.ssh/ec2-key
          chmod 644 ~/.ssh/ec2-key.pub
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUB_KEY }}

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Set up Pulumi
        uses: pulumi/actions@v5
      - name: run pulumi preview
        working-directory: pulumi
        run: |
          export PUB_KEY_LOCATION="$HOME/.ssh/ec2-key.pub"
          pulumi stack select main
          pulumi preview
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}


      - name: Verify preview succeeded
        run: echo "Pulumi preview ran successfully!"

      - name: Lint Ansible Playbooks
        working-directory: ansible
        run: |
          ansible-playbook --syntax-check playbook.yml
 deploy:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    needs: preview_and_lint
    environment:
      name: main
    steps:
      - uses: actions/checkout@v3

      - name: Debug env
        run: |
          echo "PULUMI_ACCESS_TOKEN: ${{secrets.PULUMI_ACCESS_TOKEN}}"
          echo "AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}"
      - name: Setup SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2-key
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/ec2-key.pub
          chmod 600 ~/.ssh/ec2-key
          chmod 644 ~/.ssh/ec2-key.pub
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIV_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUB_KEY }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # or whatever version you're using

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Instal pulumi
        uses: pulumi/actions@v5

      - name: Run infra provisioning
        run: |
          echo "Environment vars exported and ready for code to access"
          bash ./build.sh

        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PORT: ${{ secrets.PORT }}
          DB_URI: ${{ secrets.DB_URI}}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          USD_RESERVE: ${{ secrets.USD_RESERVE }}
          NGN_RESERVE: ${{ secrets.NGN_RESERVE }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
